AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  famyly-budget
  Sample SAM Template for famyly-budget

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      MethodSettings:
        - HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
          MetricsEnabled: true
          DataTraceEnabled: false
          ThrottlingRateLimit: 50
          ThrottlingBurstLimit: 25
      BinaryMediaTypes:
        - "application/octet-stream"
        - "multipart/form-data"
      # DefinitionBody:
      #   openapi: "3.0"
      #   info: {}
      #   paths:
      #     /readTransactions:
      #       post:
      #         x-amazon-apigateway-integration:
      #           httpMethod: POST
      #           type: aws_proxy
      #           uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ReadTransactions.Arn}/invocations
      #         responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'POST, GET'"
        MaxAge: "'600'"
  ReadTransactions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: readTransactions/
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 3008
      Timeout: 30
      Events:
        ApiPOSTreadTransactions:
          Type: Api
          Properties:
            Path: /readTransactions
            Method: POST
            RestApiId: !Ref Api

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt ReadTransactions.Arn
  ReadTransactionsFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt ReadTransactions.Arn
